#ifndef DATAFORMAT_H
#define DATAFORMAT_H

#define DATAROOM 0x00
#define DATAONEWIRE0 0x01
#define DATAONEWIRE1 0x02
#define DATAVBAT 0x03
#define DATABMEHUM 0x04
#define DATABMETEMP 0x05
#define DATABMEPRESSURE 0x06
#define DATABMEGAS 0x07
#define DATAACCELX 0x08
#define DATAACCELY 0x09
#define DATAACCELZ 0x0a
#define DATAGYROX 0x0b
#define DATAGYROY 0x0c
#define DATAGYROZ 0x0d
#define DATAACCELTEMP 0x0e
#define DATALUX 0x0f

#endif /* --- DATAFORMAT_H --- */
